sudo: false
language: node_js
node_js:
- node
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8-multilib
    - g++-4.8-multilib
    - gcc-multilib
    - g++-multilib
os:
- linux
before_install:
- sudo apt-get install libsdl2-dev
before_deploy:
- ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-`uname -m`.tar"
- npm run prebuild
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ARCH=ia32 npm run prebuild; fi
- ls -R prebuilds
- tar --create --verbose --file="$ARCHIVE_NAME" --directory prebuilds
- echo "Created archive $ARCHIVE_NAME"
  .
deploy:
  provider: releases
  draft: false
  prerelease: true
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
    tags: true
    node: node
  api_key:
    secure: "qyGthxmCMC+zRcdmSrWKQo42VxDfX2s4v6bGl1tspklEyY4y52HMUYyPjzRkktO9gNZqJxHon9TcxuakuWYrzfwPz+w1DDIGSIm4V4P/6flqiTZcZHk8zR9JHSDlGwVoyGGaNf5YcngQFSfys4SAbiHLGmHQJQKeDesF53bTX6ycUMACJAnshIi9MGGjVai//PbSm0IYPKufMwJkHEL9oD4/REpphQRa6R4ifcYSKamK90ts2RuwKOC/y4lH4gEeL3+/x/vS6Oe66x9iI6UxFaxFCGgzw7T3MfLqmt5I324GZsDjr+etUe8acGs8y5ssZPjn9TRKkI2H3/1DMHWzuP6IICxWgiPExi6c75EME9foCmGdWap+c6IU0bmz53ZI16EojlJgt2VgSOYMm7B9vfHYrUO00XhpTv2yerthvNBDJSDYxqCUAbDemdTx5NyNn1YvHgJn8mX7dmBNkT9s5m/c2V0qN4mPNEguloNEpFz3/xk7WnFLXlFYggkgL/scCAS2YutpgbCKOQRicCao/IJQl2/2eE3YofDMwBVRAYXAQTXIBlSNBRn20LW4fFToyNbU0xIkIIodjrjlavGwfCwBO0rsw/uImKYEZkl6waYbNW74wbRs1LOuSIekq8NA2rRtQE9sKKNXP4WfaQKrx0q1lZfMCrGc/eweS8jLKOY="